name: Auto Create Release

on:
  push:
    tags:
      - 'v*.*.*.*'
  workflow_dispatch:  # Add this line to allow manual trigger

permissions:
  contents: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Version ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          body: |
            ## Version ${{ steps.get_version.outputs.VERSION }}
            
            ### Changes in this release:
            - Fixed various bugs
            - Added new features
            - Improved performance
