name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Match v2.6.0 format
      - 'v*.*.*.*' # Also match four-segment versions
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Create custom zip file
        run: |
          # Remove .git directory and other unnecessary files
          rm -rf .git .github .gitignore

          # Create zip with custom name (without version)
          zip -r Clothing_Form.zip .
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Version ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          body: |
            ## Version ${{ steps.get_version.outputs.VERSION }}
            
            ### Changes in this release:
            - See the [changelog](https://github.com/abrianbaker80/Clothing_Form/blob/main/CHANGELOG.md) for details.
          files: Clothing_Form.zip
          generate_release_notes: false
          skipIfReleaseExists: false
